pipeline {
    agent any
    tools {
      terraform 'Terraform'
    }

    stages{
        stage('Git repo'){
            steps{
                checkout scmGit(branches: [[name: '*/localAWSProvider']], extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: '/TerraformEKS']]]], userRemoteConfigs: [[url: 'https://github.com/andrejpopovskiINKI73/TerraformEKSDemoV1.git']])
            }
        }
        stage('Terraform init'){
            steps{
                dir('TerraformEKS') {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform apply'){
            steps{
                dir('TerraformEKS') {
                    sh 'terraform apply --auto-approve'
                }
                
            }
        }
    }
}