pipeline {
    agent any
    tools {
      terraform 'Terraform-1'
    }
    stages{
        stage('Git repo'){
            steps{
                git credentialsId: 'Github', url: 'https://github.com/andrejpopovskiINKI73/TerraformEKSDemoV1/tree/master/TerraformEKS'
            }
        }
        stage('Terraform init'){
            steps{
                powershell 'terraform init'
            }
        }
        stage('Terraform apply'){
            steps{
                powershell 'terraform apply --auto-apporve'
            }
        }
    }
}